name: Migrate LFS Data

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repo to LFS migrate'
        required: true
        type: string
      issue_number:
        description: 'Issue number for reporting'
        required: true
        type: string
      batch_number:
        description: 'Batch number for context'
        required: true
        type: string

permissions:
  contents: read
  issues: write

jobs:
  migrate-lfs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Extract repository name
      id: repo-info
      run: |
        REPO_NAME=$(basename "${{ inputs.repository }}")
        echo "name=$REPO_NAME" >> $GITHUB_OUTPUT
    
    - name: Report LFS migration start
      if: inputs.issue_number != ''
      uses: actions/github-script@v8
      with:
        script: |
          await github.rest.issues.createComment({
            issue_number: ${{ inputs.issue_number }},
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `### 📦 LFS Migration Starting
            
**Repository:** \`${{ steps.repo-info.outputs.name }}\`
${context.payload.inputs.batch_number ? `**Batch:** ${context.payload.inputs.batch_number}` : ''}

Migrating Git LFS objects to the target repository...`
          });
    
    - name: Install gh migrate-lfs extension
      run: gh extension install mona-actions/gh-migrate-lfs
      env:
        GH_TOKEN: ${{ secrets.TARGET_ADMIN_TOKEN }}
    
    - name: Migrate LFS objects to target repository
      id: migrate
      run: |
        # Uncomment and configure for production use:
        # gh migrate-lfs sync \
        #   --file ${{ inputs.repository }} \
        #   --target-organization ${{ vars.TARGET_ORGANIZATION }} \
        #   --target-token ${{ secrets.TARGET_ADMIN_TOKEN }} \
        #   --work-dir lfs/
        
        # For now, just show help (remove in production)
        gh migrate-lfs sync --help
        echo "lfs_status=success" >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ secrets.TARGET_ADMIN_TOKEN }}
    
    - name: Report LFS migration completion
      if: always() && inputs.issue_number != ''
      uses: actions/github-script@v8
      with:
        script: |
          const success = '${{ steps.migrate.outputs.lfs_status }}' === 'success';
          const icon = success ? '✅' : '❌';
          const status = success ? 'completed successfully' : 'failed';
          
          await github.rest.issues.createComment({
            issue_number: ${{ inputs.issue_number }},
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `### ${icon} LFS Migration ${status}
            
**Repository:** \`${{ steps.repo-info.outputs.name }}\`
${context.payload.inputs.batch_number ? `**Batch:** ${context.payload.inputs.batch_number}` : ''}
**Duration:** ${Math.round((Date.now() - ${{ job.started_at }} * 1000) / 60000)} minutes

${success ? '✅ All Git LFS objects have been migrated to the target repository.' : '⚠️ Please check the workflow logs for error details.'}`
          });