name: Migrate Releases

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository to migrate releases from'
        required: true
        type: string

jobs:
  migrate-releases:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install gh migrate-releases extension
      run: gh extension install mona-actions/gh-migrate-releases
      env:
        GH_TOKEN: ${{ secrets.TARGET_ADMIN_TOKEN }}

    - name: Migrate releases to target repository
      run: |
        gh migrate-releases sync \
          --repository ${{ inputs.repo }} \
          --source-organization ${{ vars.SOURCE_ORGANIZATION }} \
          --source-token ${{ secrets.SOURCE_ADMIN_TOKEN }} \
          --target-organization ${{ vars.TARGET_ORGANIZATION }} \
          --target-token ${{ secrets.TARGET_ADMIN_TOKEN }}
