name: Migration Batch Processor

permissions:
  contents: read
  actions: read
  issues: write

on:
  repository_dispatch:
    types: [migration-batch]

jobs:
  process-repository-migrations:
    name: Batch ${{ github.event.client_payload.batch.batchNumber }} - ${{ matrix.repository }}
    runs-on: self-hosted
    strategy:
      matrix:
        repository: ${{ github.event.client_payload.batch.repositories }}
      fail-fast: false
      max-parallel: 10
    timeout-minutes: 50400
    
    env:
      TARGET_ORG: ${{ github.event.client_payload.batch.targetOrganization }}
      BATCH_NUMBER: ${{ github.event.client_payload.batch.batchNumber }}
      MIGRATION_TYPE: ${{ github.event.client_payload.batch.migrationType }}
      VISIBILITY: ${{ github.event.client_payload.batch.targetRepositoryVisibility }}
      TOTAL_BATCHES: ${{ github.event.client_payload.batch.totalBatches }}
      ORCHESTRATOR_RUN_ID: ${{ github.event.client_payload.orchestrator_run_id }}
      INSTALL_PREREQS: ${{ github.event.client_payload.batch.installPrereqs || 'false' }}
      REPOSITORY: ${{ matrix.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract repository name and path
        id: repo-info
        run: |
          REPO_NAME=$(basename "${{ matrix.repository }}")
          REPO_PATH=$(echo "${{ matrix.repository }}" | sed -E 's#https?://[^/]+/##')
          echo "name=$REPO_NAME" >> $GITHUB_OUTPUT
          echo "path=$REPO_PATH" >> $GITHUB_OUTPUT

      - name: Install GEI prerequisites
        if: env.INSTALL_PREREQS == 'true'
        run: |
          sudo apt-get update && sudo apt-get install -y \
            git unzip curl wget apt-transport-https software-properties-common
          
          if ! command -v gei &> /dev/null; then
            wget -q https://github.com/github/gh-gei/releases/latest/download/gei-linux-amd64
            sudo install --owner root --group root --mode 755 gei-linux-amd64 /usr/local/bin/gei
          fi
          
          echo "GEI Version: $(gei --version)"

      - name: Execute GEI migration for ${{ matrix.repository }}
        id: migrate
        run: |
          ARGS=(
            ".github/scripts/migration/gei-migrate.js"
            "--repository" "$REPOSITORY"
            "--target-org" "$TARGET_ORG"
            "--visibility" "$VISIBILITY"
            "--migration-type" "$MIGRATION_TYPE"
            "--batch-number" "$BATCH_NUMBER"
            "--total-batches" "$TOTAL_BATCHES"
          )
          
          # Add lock flag for production migrations
          if [[ "$MIGRATION_TYPE" == "production" ]]; then
            ARGS+=("--lock-source-repo")
          fi
          
          node "${ARGS[@]}"
        env:
          GH_PAT: ${{ secrets.TARGET_ADMIN_TOKEN }}
          GH_SOURCE_PAT: ${{ secrets.SOURCE_ADMIN_TOKEN }}

      - name: Detect LFS, packages, and releases requirements
        id: migration-checks
        run: |
          # Check LFS
          if node .github/scripts/migration/check-repo.cjs lfs.csv "${{ matrix.repository }}" | grep -q "found=true"; then
            echo "lfs=true" >> $GITHUB_OUTPUT
          else
            echo "lfs=false" >> $GITHUB_OUTPUT
          fi
          
          # Check packages
          if node .github/scripts/migration/check-repo.cjs packages.csv "${{ matrix.repository }}" | grep -q "found=true"; then
            echo "packages=true" >> $GITHUB_OUTPUT
          else
            echo "packages=false" >> $GITHUB_OUTPUT
          fi
          
          # Check releases
          RELEASES_DIR="/opt/migration/releases/${{ steps.repo-info.outputs.path }}"
          if [ -d "$RELEASES_DIR" ]; then
            echo "releases=true" >> $GITHUB_OUTPUT
          else
            echo "releases=false" >> $GITHUB_OUTPUT
          fi

      - name: Trigger LFS data migration
        if: steps.migration-checks.outputs.lfs == 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: post/lfs.yml
          token: ${{ secrets.TARGET_ADMIN_TOKEN }}
          inputs: '{"repository": "${{ matrix.repository }}"}'

      - name: Trigger packages data migration
        if: steps.migration-checks.outputs.packages == 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: post/packages.yml
          token: ${{ secrets.TARGET_ADMIN_TOKEN }}
          inputs: '{"repository": "${{ matrix.repository }}"}'

      - name: Trigger releases data migration
        if: steps.migration-checks.outputs.releases == 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: post/releases.yml
          token: ${{ secrets.TARGET_ADMIN_TOKEN }}
          inputs: '{"repo": "${{ steps.repo-info.outputs.path }}"}'

      - name: Map mannequin users to real accounts
        if: hashFiles('user-mappings-gei.csv') != ''
        continue-on-error: true
        run: |
          gei reclaim-mannequin \
            --csv user-mappings-gei.csv \
            --github-target-org ${{ env.TARGET_ORG }} \
            --github-target-pat ${{ secrets.TARGET_ADMIN_TOKEN }}

      - name: Save repository migration result
        if: always()
        run: |
          # Create status file
          STATUS_FILE="${{ steps.repo-info.outputs.name }}.txt"
          echo "${{ matrix.repository }}, ${{ job.status }}" > "$STATUS_FILE"
          
          # Also add to job summary for easy viewing
          echo "| ${{ matrix.repository }} | ${{ job.status }} |" >> $GITHUB_STEP_SUMMARY

      - name: Upload status artifact for batch aggregation
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: migration-status-batch-${{ env.BATCH_NUMBER }}-${{ steps.repo-info.outputs.name }}
          path: ${{ steps.repo-info.outputs.name }}.txt
          retention-days: 7

  generate-batch-report:
    name: Batch ${{ github.event.client_payload.batch.batchNumber }} Summary
    runs-on: ubuntu-latest
    needs: [process-repository-migrations]
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all repository status artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: migration-status-batch-${{ github.event.client_payload.batch.batchNumber }}-*
          path: batch-${{ github.event.client_payload.batch.batchNumber }}-status
          merge-multiple: true

      - name: Generate batch completion report
        uses: actions/github-script@v8
        env:
          BATCH_INFO: ${{ toJson(github.event.client_payload.batch) }}
        with:
          script: |
            const script = require('./.github/scripts/orchestration/batch-status.js');
            return await script({github, context, core});

      - name: Save batch summary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: batch-${{ github.event.client_payload.batch.batchNumber }}-status
          path: batch-${{ github.event.client_payload.batch.batchNumber }}-status.json
