name: Migrate LFS Data

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repo to LFS migrate'
        required: true
        type: string
      issue_number:
        description: 'Issue number for reporting'
        required: true
        type: string
      batch_number:
        description: 'Batch number for context'
        required: true
        type: string

permissions:
  contents: read
  issues: write

jobs:
  migrate-lfs:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Extract repository name
      id: repo-info
      run: |
        REPO_NAME=$(basename "${{ inputs.repository }}")
        echo "name=$REPO_NAME" >> $GITHUB_OUTPUT
    
    - name: Report LFS migration start
      if: ${{ inputs.issue_number != '' }}
      uses: actions/github-script@v8
      with:
        script: |
          const batchInfo = context.payload.inputs.batch_number ? 
            `**Batch:** ${context.payload.inputs.batch_number}` : '';
          
          const message = [
            '### 📦 LFS Migration Starting',
            '',
            `**Repository:** \`${{ steps.repo-info.outputs.name }}\``,
            batchInfo,
            '',
            'Migrating Git LFS objects to the target repository...'
          ].filter(line => line !== '').join('\n');
          
          await github.rest.issues.createComment({
            issue_number: ${{ inputs.issue_number }},
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          });
    
    - name: Install gh migrate-lfs extension
      run: gh extension install mona-actions/gh-migrate-lfs
      env:
        GH_TOKEN: ${{ secrets.TARGET_ADMIN_TOKEN }}

    - name: Prepare LFS migration
      env:
        CLONE_URL: ${{ inputs.repository }}.git
        LFS_CSV_PATH: lfs.csv
      run: |
          node .github/scripts/filters/lfs.js extract
    
    - name: Migrate LFS objects to target repository
      id: migrate
      run: |
        gh migrate-lfs sync \
          --file ${{ inputs.repository }}.csv \
          --target-organization ${{ vars.TARGET_ORGANIZATION }} \
          --target-token ${{ secrets.TARGET_ADMIN_TOKEN }} \
          --work-dir ${{ vars.LOCAL_CACHE_DIR }}/lfs
        
        echo "lfs_status=success" >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ secrets.TARGET_ADMIN_TOKEN }}
    
    - name: Report LFS migration completion
      if: ${{ always() && inputs.issue_number != '' }}
      uses: actions/github-script@v8
      with:
        script: |
          const success = '${{ steps.migrate.outputs.lfs_status }}' === 'success';
          const icon = success ? '✅' : '❌';
          const status = success ? 'completed successfully' : 'failed';
          const batchInfo = context.payload.inputs.batch_number ? 
            `**Batch:** ${context.payload.inputs.batch_number}` : '';
          
          const statusMessage = success 
            ? '✅ All Git LFS objects have been migrated to the target repository.' 
            : '⚠️ Please check the workflow logs for error details.';
          
          const message = [
            `### ${icon} LFS Migration ${status}`,
            '',
            `**Repository:** \`${{ steps.repo-info.outputs.name }}\``,
            batchInfo,
            '',
            statusMessage
          ].filter(line => line !== '').join('\n');
          
          await github.rest.issues.createComment({
            issue_number: ${{ inputs.issue_number }},
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          });