name: Repos Migration (Prepare)

on:
  issues:
    types: [opened, edited]

permissions:
  contents: read
  issues: write
  actions: write

jobs:
  validate-and-initialize-issue:
    name: Prepare Repos Migration
    runs-on: ubuntu-latest

    if: github.event_name == 'issues' &&
      (github.event.action == 'opened' || github.event.action == 'edited') &&
      contains(github.event.issue.labels.*.name, 'migration') &&
      contains(github.event.issue.labels.*.name, 'batch') &&
      !contains(github.event.issue.labels.*.name, 'gei-org')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract repositories and settings from issue
        id: parse-issue-body
        uses: stefanbuck/github-issue-parser@v3

      - name: "Debug: Display parsed issue data"
        run: echo $JSON_STRING
        env:
          JSON_STRING: ${{ steps.parse-issue-body.outputs.jsonString }}
        
      - name: Post migration setup instructions
        uses: actions/github-script@v8
        with:
          script: |
            const script = require('./.github/scripts/reporting/init-issue.js');
            return await script({github, context});
        env:
          REPOSITORIES: ${{ steps.parse-issue-body.outputs.issueparser_repositories }}
          VISIBILITY: ${{ steps.parse-issue-body.outputs.issueparser_target_repository_visibility }}
          TARGET_ORG: ${{ vars.TARGET_ORGANIZATION }}
          TARGET_ADMIN_TOKEN: ${{ secrets.TARGET_ADMIN_TOKEN }}

      - name: Report issue parsing error
        if: ${{ failure() }}
        uses: actions/github-script@v8
        with:
          script: |
            let commentBody
            commentBody = `😢 The issue body could not be parsed. Please edit the issue body or open a new issue using an issue template.`
            await github.rest.issues.createComment({
              issue_number: ${{ github.event.issue.number }},
              owner: '${{ github.REPOSITORY_OWNER }}',
              repo: '${{ github.event.repository.name }}',
              body: commentBody
            })
