name: Repositories Migration to GHEC [GEI] (Batched)

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: write
  actions: write

jobs:
  initiate-migration-orchestration:
    if: contains(github.event.comment.body, '/run-dry-run-migration') ||
        contains(github.event.comment.body, '/run-production-migration')
    uses: ./.github/workflows/orchestrator.yml
    with:
      TARGET_ORGANIZATION: ${{ vars.TARGET_ORGANIZATION }}
      RUNNER: ubuntu-latest
      INSTALL_PREREQS: ${{ vars.INSTALL_PREREQS }}
      BATCH_SIZE: 250
      MIGRATION_TYPE: ${{ contains(github.event.comment.body, 'dry-run') && 'dry-run' || 'production' }}
    secrets:
      TARGET_ADMIN_TOKEN: ${{ secrets.TARGET_ADMIN_TOKEN }}
      SOURCE_ADMIN_TOKEN: ${{ secrets.SOURCE_ADMIN_TOKEN }}
      AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}      
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
